# Generated by Django 4.1.2 on 2022-11-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Torrent", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="premium",
            field=models.BooleanField(default=False),
        ),
    ]
