# Generated by Django 4.1.2 on 2022-11-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Torrent", "0002_user_premium"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(default="user.png", upload_to="user_image"),
        ),
    ]
