# Generated by Django 4.1.2 on 2022-12-04 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Torrent", "0005_torrent_completed"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gdrive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                ("size", models.IntegerField()),
                ("gid", models.TextField()),
                ("dirid", models.TextField()),
                ("hash", models.CharField(max_length=40)),
                (
                    "torrentid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Torrent.torrent",
                    ),
                ),
                (
                    "userid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Torrent.user"
                    ),
                ),
            ],
        ),
    ]
